permalink:           pretty
#relative_permalinks: false

# Setup
title:               AAA
description:         'dd'
url:                 
baseurl:             '/blog/'
paginate:            5

kramdown:
  input: GFM


# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
