title: vida
baseurl: "https:/tybrain.github.io/"
relative_permalinks: false

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname:
