permalink:           pretty
relative_permalinks: false

# Setup
title:               AAA
tagline:             'A Jekyll theme'
description:         'dd'
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
